steps:
  - id: "Gerando service-account-storage.json"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=./backend/storage/credentials/google/service-account-storage.json.enc
      - --plaintext-file=./backend/storage/credentials/google/service-account-storage.json
      - --location=global
      - --keyring=testing-lesson
      - --key=service-account

  - id: "Rodando *** docker-compose"
    name: "docker/compose"
    args: ["-f", "docker-compose.prod.yaml", "up", "-d"]
    env:
      - GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID
      - GOOGLE_CLOUD_KEY_FILE=service-account-storage.json
      - GOOGLE_CLOUD_STORAGE_BUCKET=codeflix-storage
      - GOOGLE_CLOUD_STORAGE_API_URI=https://storage.cloud.google.com/codeflix-storage
      - TESTING_PROD=true

  - id: "Chown in /var/www"
    name: "docker"
    args:
      [
        "exec",
        "-u",
        "root",
        "-t",
        "micro-videos-app",
        "chown",
        "-R",
        "www-data:www-data",
        "/var/www",
      ]

  - id: "Rodando composer"
    name: "docker"
    args: ["exec", "-t", "micro-videos-app", "composer", "install", "-d", "/var/www/backend"]

  - id: "Copying .env"
    name: "docker"
    args: ["exec", "-t", "micro-videos-app", "cp", "/var/www/backend/.env.example", "/var/www/backend/.env"]

  - id: "Copying .env.testing"
    name: "docker"
    args:
      [
        "exec",
        "-t",
        "micro-videos-app",
        "cp",
        "/var/www/backend/.env.testing.example",
        "/var/www/backend/.env.testing",
      ]

  - id: "Running key:generate"
    name: "docker"
    args:
      [
        "exec",
        "-t",
        "micro-videos-app",
        "php",
        "/var/www/backend/artisan",
        "key:generate",
      ]

  - id: "Running migrations"
    name: "docker"
    args:
      ["exec", "-t", "micro-videos-app", "php", "/var/www/backend/artisan", "migrate"]

  - id: "Running Phpunit"
    name: "docker"
    args:
      [
        "exec",
        "-t",
        "micro-videos-app",
        "/var/www/backend/vendor/bin/phpunit",
        "-c",
        "/var/www/backend/phpunit.xml",
      ]
